create table if not exists private.perception_synthetic_test_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  iterations integer not null check (iterations between 1 and 100),
  total_checks integer not null default 0,
  passed_checks integer not null default 0,
  failed_checks integer not null default 0,
  status text not null default 'running' check (status in ('running','pass','fail','error')),
  target_user_id uuid,
  target_project_id uuid,
  checks jsonb not null default '{}'::jsonb,
  row_counts_before jsonb not null default '{}'::jsonb,
  row_counts_after jsonb not null default '{}'::jsonb,
  error_code text,
  created_at timestamptz not null default now()
);

revoke all on table private.perception_synthetic_test_runs
  from public, anon, authenticated;

create or replace function private.perception_run_synthetic_tests(
  p_iterations integer default 25
)
returns bigint
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
  v_iterations integer := greatest(1, least(coalesce(p_iterations,25),100));
  v_run_id bigint;
  v_owner uuid;
  v_project uuid;
  v_project_name text;
  v_other uuid;
  v_result jsonb;
  v_visible integer;
  v_i integer;
  v_owner_preview_pass integer := 0;
  v_owner_warm_pass integer := 0;
  v_cross_preview_pass integer := 0;
  v_cross_rls_pass integer := 0;
  v_operator_pass integer := 0;
  v_privilege_pass integer := 0;
  v_total integer := 0;
  v_pass integer := 0;
  v_fail integer := 0;
  v_before jsonb;
  v_after jsonb;
  v_role_changed boolean := false;
begin
  select p.user_id, p.id, p.name
  into v_owner, v_project, v_project_name
  from public.perception_projects p
  where p.active is true
    and exists (
      select 1
      from public.perception_scenarios s
      where s.user_id=p.user_id
        and s.project_id=p.id
        and s.status='active'
        and s.expires_at > now()
    )
  order by p.updated_at desc
  limit 1;

  if v_owner is null or v_project is null then
    raise exception 'No active Project World with fresh Scenario Forge memory is available';
  end if;

  select id
  into v_other
  from auth.users
  where id <> v_owner
  order by created_at
  limit 1;

  if v_other is null then
    raise exception 'No second user is available for isolation testing';
  end if;

  select jsonb_build_object(
    'projects', (select count(*) from public.perception_projects),
    'objectives', (select count(*) from public.perception_objectives),
    'routes', (select count(*) from public.perception_routes),
    'route_nodes', (select count(*) from public.perception_route_nodes),
    'scenarios', (select count(*) from public.perception_scenarios),
    'execution_ledger', (select count(*) from public.perception_execution_ledger),
    'epistemic_ledger', (select count(*) from public.perception_epistemic_ledger),
    'worker_runs', (select count(*) from public.perception_worker_runs)
  ) into v_before;

  insert into private.perception_synthetic_test_runs(
    iterations,target_user_id,target_project_id,row_counts_before
  )
  values(v_iterations,v_owner,v_project,v_before)
  returning id into v_run_id;

  for v_i in 1..v_iterations loop
    begin
      perform set_config('request.jwt.claim.sub',v_owner::text,true);
      execute 'set local role authenticated';
      v_role_changed := true;

      v_result := public.perception_preview_intent_shadow(
        coalesce(v_project_name,'Perception') || ' synthetic ' || (v_i % 11)::text,
        'perceive',
        3
      );

      if v_result->>'source'='intent_shadow_v0_8'
         and coalesce((v_result->>'ephemeral')::boolean,false)
         and (v_result->>'candidate_count')::integer >= 1
         and exists (
           select 1
           from jsonb_array_elements(v_result->'candidates') c
           where c->>'project_id'=v_project::text
         ) then
        v_owner_preview_pass := v_owner_preview_pass + 1;
      end if;

      execute 'reset role';
      v_role_changed := false;
    exception when others then
      if v_role_changed then
        execute 'reset role';
        v_role_changed := false;
      end if;
    end;

    begin
      perform set_config('request.jwt.claim.sub',v_owner::text,true);
      execute 'set local role authenticated';
      v_role_changed := true;

      v_result := public.perception_get_warm_start(
        v_project,
        coalesce(v_project_name,'Perception') || ' continuation ' || (v_i % 13)::text,
        3
      );

      if v_result->>'source'='scenario_forge_v0_6'
         and (v_result->>'scenario_count')::integer >= 1
         and not exists (
           select 1
           from jsonb_array_elements(v_result->'scenarios') s
           where coalesce((s->'route_seed'->>'must_revalidate')::boolean,false) is not true
              or coalesce((s->>'is_fresh')::boolean,false) is not true
         ) then
        v_owner_warm_pass := v_owner_warm_pass + 1;
      end if;

      execute 'reset role';
      v_role_changed := false;
    exception when others then
      if v_role_changed then
        execute 'reset role';
        v_role_changed := false;
      end if;
    end;

    begin
      perform set_config('request.jwt.claim.sub',v_other::text,true);
      execute 'set local role authenticated';
      v_role_changed := true;

      v_result := public.perception_preview_intent_shadow(
        coalesce(v_project_name,'Perception') || ' synthetic isolation ' || (v_i % 7)::text,
        'perceive',
        5
      );

      if not exists (
        select 1
        from jsonb_array_elements(v_result->'candidates') c
        where c->>'project_id'=v_project::text
      ) then
        v_cross_preview_pass := v_cross_preview_pass + 1;
      end if;

      select count(*)
      into v_visible
      from public.perception_projects
      where id=v_project;

      if v_visible=0 then
        v_cross_rls_pass := v_cross_rls_pass + 1;
      end if;

      execute 'reset role';
      v_role_changed := false;
    exception when others then
      if v_role_changed then
        execute 'reset role';
        v_role_changed := false;
      end if;
    end;
  end loop;

  if exists(
       select 1 from public.perception_operator_principals
       where user_id=v_owner
         and capability='code'
         and enabled=true
     )
     and exists(
       select 1 from public.perception_sources
       where user_id=v_owner
         and provider='github'
         and source_type='github_repo'
         and enabled=true
     ) then
    v_operator_pass := 1;
  end if;

  if not has_function_privilege('anon','public.perception_get_warm_start(uuid,text,integer)','execute')
     and not has_function_privilege('authenticated','public.perception_refresh_scenario_forge_internal(uuid,uuid)','execute')
     and not has_function_privilege('anon','public.perception_refresh_scenario_forge_internal(uuid,uuid)','execute')
     and not has_function_privilege('anon','public.perception_score_forecast_resolution_trigger()','execute')
     and not has_function_privilege('authenticated','public.perception_score_forecast_resolution_trigger()','execute')
     and not has_function_privilege('anon','public.perception_sync_resolution_proposals()','execute')
     and not has_function_privilege('authenticated','public.perception_sync_resolution_proposals()','execute')
     and not has_table_privilege('anon','public.perception_operator_principals','select')
     and not has_table_privilege('authenticated','public.perception_operator_principals','select') then
    v_privilege_pass := 1;
  end if;

  select jsonb_build_object(
    'projects', (select count(*) from public.perception_projects),
    'objectives', (select count(*) from public.perception_objectives),
    'routes', (select count(*) from public.perception_routes),
    'route_nodes', (select count(*) from public.perception_route_nodes),
    'scenarios', (select count(*) from public.perception_scenarios),
    'execution_ledger', (select count(*) from public.perception_execution_ledger),
    'epistemic_ledger', (select count(*) from public.perception_epistemic_ledger),
    'worker_runs', (select count(*) from public.perception_worker_runs)
  ) into v_after;

  v_total := (v_iterations * 4) + 3;
  v_pass := v_owner_preview_pass + v_owner_warm_pass + v_cross_preview_pass + v_cross_rls_pass
            + v_operator_pass + v_privilege_pass
            + case when v_before=v_after then 1 else 0 end;
  v_fail := v_total-v_pass;

  update private.perception_synthetic_test_runs
  set finished_at=now(),
      total_checks=v_total,
      passed_checks=v_pass,
      failed_checks=v_fail,
      status=case when v_fail=0 then 'pass' else 'fail' end,
      checks=jsonb_build_object(
        'owner_intent_shadow',jsonb_build_object('passed',v_owner_preview_pass,'expected',v_iterations),
        'owner_warm_start',jsonb_build_object('passed',v_owner_warm_pass,'expected',v_iterations),
        'cross_user_intent_shadow',jsonb_build_object('passed',v_cross_preview_pass,'expected',v_iterations),
        'cross_user_rls',jsonb_build_object('passed',v_cross_rls_pass,'expected',v_iterations),
        'operator_attachment_preconditions',jsonb_build_object('passed',v_operator_pass,'expected',1),
        'privilege_boundaries',jsonb_build_object('passed',v_privilege_pass,'expected',1),
        'no_row_drift',jsonb_build_object('passed',case when v_before=v_after then 1 else 0 end,'expected',1)
      ),
      row_counts_after=v_after
  where id=v_run_id;

  delete from private.perception_synthetic_test_runs
  where created_at < now()-interval '30 days';

  return v_run_id;
exception when others then
  if v_role_changed then
    execute 'reset role';
  end if;

  if v_run_id is not null then
    update private.perception_synthetic_test_runs
    set finished_at=now(),
        status='error',
        error_code=sqlstate
    where id=v_run_id;
  end if;
  raise;
end;
$$;

revoke all on function private.perception_run_synthetic_tests(integer)
  from public, anon, authenticated;

do $$
declare
  v_job_id bigint;
begin
  select jobid into v_job_id
  from cron.job
  where jobname='perception-synthetic-tests';

  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  perform cron.schedule(
    'perception-synthetic-tests',
    '7,37 * * * *',
    $cron$select private.perception_run_synthetic_tests(25);$cron$
  );
end;
$$;
